[workspace]
resolver = "3"
members = ["fed-tickets"]

[workspace.lints.rust]
ambiguous_negative_literals = "deny"
meta_variable_misuse = "deny"
missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
redundant_imports = "warn"
redundant_lifetimes = "warn"
trivial_casts = "deny"
unit-bindings = "deny"
unnameable_types = "deny"
unsafe_code = "forbid"
unused_crate_dependencies = "warn"
unused_extern_crates = "warn"
unused_import_braces = "warn"
unused_lifetimes = "warn"
unused_macro_rules = "warn"
unused_qualifications = "warn"

[workspace.lints.clippy]
pedantic = { level = "deny", priority = -69 }

allow_attributes_without_reason = "deny"
as_pointer_underscore = "deny"
as_underscore = "deny"
cfg_not_test = "deny"
clone_on_ref_ptr = "deny"
default_numeric_fallback = "deny"
deref_by_slicing = "deny"
doc_paragraphs_missing_punctuation = "deny"
empty_enum_variants_with_brackets = "deny"
empty_structs_with_brackets = "deny"
expect_used = "deny"
field_scoped_visibility_modifiers = "deny"
filetype_is_file = "deny"
float_cmp_const = "deny"
if_then_some_else_none = "deny"
indexing_slicing = "deny"
let_underscore_untyped = "deny"
lossy_float_literal = "deny"
mem_forget = "deny"
min_ident_chars = "deny"
missing_assert_message = "deny"
module_name_repetitions = "deny"
mutex_atomic = "deny"
needless_raw_strings = "deny"
non_zero_suggestions = "deny"
panic = "deny"
pub_without_shorthand = "deny"
rc_buffer = "deny"
rc_mutex = "deny"
redundant_test_prefix = "deny"
redundant_type_annotations = "deny"
renamed_function_params = "deny"
same_name_method = "deny"
self_named_module_files = "deny"
semicolon_inside_block = "deny"
single_char_lifetime_names = "deny"
str_to_string = "deny"
tests_outside_test_module = "deny"
todo = "deny"
try_err = "deny"
unimplemented = "deny"
unused_result_ok = "deny"
unused_trait_names = "warn"
unwrap_used = "deny"
