[workspace]
resolver = "3"
members = ["fed-auth", "fed-auth-verifier", "minilith", "minilith-errors"]

[workspace.dependencies]
base64 = "0.22.1"
color-eyre = "0.6.5"
dotenvy = "0.15.7"
jsonwebtoken = { version = "10.3.0", default-features = false, features = ["rust_crypto", "use_pem"] }
lettre = { version = "0.11.22", default-features = false, features = ["builder", "pool", "ring", "smtp-transport", "tokio1-rustls", "webpki-roots"] }
poem = { version = "3.1.12", features = ["cookie", "embed"] }
# we don't pull in `sqlx` here, even though it'd make our lives a bit easier,
# since it pulls in the mysql & sqlite drivers which makes compile time be slow
poem-openapi = { version = "5.1.16", features = ["swagger-ui", "uuid", "time"] }
rand = "0.10.1"
reqwest = "0.13.3"
rust-embed = "8.11.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio", "migrate", "time", "uuid"] }
tokio = { version = "1.52.1" }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
uuid = { version = "1.23.1", features = ["fast-rng", "v4"] }

[workspace.lints.rust]
ambiguous_negative_literals = "deny"
meta_variable_misuse = "deny"
missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
redundant_imports = "warn"
redundant_lifetimes = "warn"
trivial_casts = "deny"
unit-bindings = "deny"
unnameable_types = "deny"
unsafe_code = "forbid"
# doesn't work, let's say I have a library which uses all these and then a main.rs which uses that
# library, I get an error!
# See: https://doc.rust-lang.org/beta/nightly-rustc/rustc_lint_defs/builtin/static.UNUSED_CRATE_DEPENDENCIES.html#explanation
# unused_crate_dependencies = "warn"
# unused_extern_crates = "warn"
unused_import_braces = "warn"
unused_lifetimes = "warn"
unused_macro_rules = "warn"
unused_qualifications = "warn"

[workspace.lints.clippy]
pedantic = { level = "deny", priority = -69 }

allow_attributes_without_reason = "deny"
as_pointer_underscore = "deny"
as_underscore = "deny"
cfg_not_test = "deny"
clone_on_ref_ptr = "deny"
default_numeric_fallback = "deny"
deref_by_slicing = "deny"
doc_paragraphs_missing_punctuation = "deny"
empty_enum_variants_with_brackets = "deny"
empty_structs_with_brackets = "deny"
expect_used = "deny"
field_scoped_visibility_modifiers = "deny"
filetype_is_file = "deny"
float_cmp_const = "deny"
if_then_some_else_none = "deny"
indexing_slicing = "deny"
let_underscore_untyped = "deny"
lossy_float_literal = "deny"
mem_forget = "deny"
min_ident_chars = "deny"
missing_assert_message = "deny"
module_name_repetitions = "deny"
mutex_atomic = "deny"
needless_raw_strings = "deny"
non_zero_suggestions = "deny"
panic = "deny"
pub_without_shorthand = "deny"
rc_buffer = "deny"
rc_mutex = "deny"
redundant_test_prefix = "deny"
redundant_type_annotations = "deny"
renamed_function_params = "deny"
same_name_method = "deny"
self_named_module_files = "deny"
semicolon_inside_block = "deny"
#single_char_lifetime_names = "deny"
str_to_string = "deny"
tests_outside_test_module = "deny"
todo = "deny"
try_err = "deny"
unimplemented = "deny"
unused_result_ok = "deny"
unused_trait_names = "warn"
unwrap_used = "deny"
