name: fed-dev

include:
  - compose.base.yaml

volumes:
  postgres-storage:
  rustfs-storage:

services:
  fed-postgres:
    volumes:
      - postgres-storage:/var/lib/postgres
    ports:
      - 5432:5432

  fed-collector:
    ports:
      - 4317:4317
      - 55679:55679

  fed-loki-init:

  fed-loki:
    ports:
      - 3100:3100

  fed-grafana:
    ports:
      - "3000:3000"

  fed-prometheus:
    ports:
      - 9090:9090

  fed-tempo:
    ports:
      - "3200:3200"

  fed-s3:
    # default password: rustfsadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - rustfs-storage:/data
