[package]
name = "minilith"
version = "0.1.0"
edition = "2024"

[dependencies]
a2 = { version = "0.10.0", default-features = false, features = ["ring", "tracing"] }
base64.workspace = true
bin-common = { version = "0.1.0", path = "../bin-common" }
# NOTE: this doesn't verify authenticity: i.e. that the encrypted data comes from someone with the key (us)
# this is not needed for user data encryption because we don't need to validate the integrity of the data,
# the only purpose is to anonymise it.
chacha20 = "0.10.0"
color-eyre.workspace = true
dotenvy.workspace = true
fcm-service = "0.2.3"
fed-auth-verifier.path = "../fed-auth-verifier"
minilith-errors = { version = "0.1.0", path = "../minilith-errors", features = ["sqlx"] }
opentelemetry.workspace = true
opentelemetry-appender-tracing.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry_sdk.workspace = true
poem.workspace = true
poem-openapi.workspace = true
rand.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json = "1.0.149"
serde_with = "3.20.0"
sqlx.workspace = true
sqlx-tracing.workspace = true
time.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[dev-dependencies]
jsonwebtoken.workspace = true
poem = { workspace = true, features = ["test"] }

[lints]
workspace = true
