[package]
name = "minilith"
version = "0.1.0"
edition = "2024"

[dependencies]
base64.workspace = true
# NOTE: this doesn't verify authenticity: i.e. that the encrypted data comes from someone with the key (us)
# this is not needed for user data encryption because we don't need to validate the integrity of the data,
# the only purpose is to anonymise it.
chacha20 = "0.10.0"
color-eyre.workspace = true
dotenvy.workspace = true
fed-auth-verifier.path = "../fed-auth-verifier"
minilith-errors = { version = "0.1.0", path = "../minilith-errors" }
poem.workspace = true
poem-openapi.workspace = true
rand.workspace = true
serde.workspace = true
serde_json = "1.0.149"
serde_with = "3.20.0"
sqlx.workspace = true
time = { version = "0.3", features = ["parsing", "formatting"] }
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[dev-dependencies]
poem = { workspace = true, features = ["test"] }

[lints]
workspace = true
