[package]
name = "transactions"
version = "0.1.0"
edition = "2024"

[dependencies]
async-stripe = { version = "1.0.0-rc.6", default-features = false, features = ["redact-generated-debug", "rustls-ring", "rustls-tls-webpki-roots"] }
async-stripe-checkout = { version = "1.0.0-rc.6", features = ["checkout_session", "redact-generated-debug"] }
async-stripe-core = { version = "1.0.0-rc.6", default-features = false, features = ["customer", "redact-generated-debug"] }
async-stripe-misc = { version = "1.0.0-rc.6", features = ["webhook_endpoint", "redact-generated-debug"] }
# async-stripe-payment = { version = "1.0.0-rc.6", features = ["card", "payment_link"] }
async-stripe-types = { version = "1.0.0-rc.6", features = ["redact-generated-debug"] }
async-stripe-webhook = { version = "1.0.0-rc.6", features = ["redact-generated-debug"] }
base64.workspace = true
bin-common = { path = "../bin-common" }
color-eyre.workspace = true
dashmap = "6.2.1"
dotenvy.workspace = true
ed25519-dalek.workspace = true
fed-auth-verifier = { path = "../fed-auth-verifier" }
jsonwebtoken.workspace = true
minilith-errors = { version = "0.1.0", path = "../minilith-errors", features = ["sqlx"] }
opentelemetry.workspace = true
poem.workspace = true
poem-openapi.workspace = true
reqwest = { workspace = true, features = ["form", "multipart", "query"] }
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
time.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing.workspace = true
typst.workspace = true
typst-kit.workspace = true
typst-layout.workspace = true
typst-pdf.workspace = true
uuid.workspace = true

[dev-dependencies]
poem = { workspace = true, features = ["test"] }

[lints]
workspace = true
