[package]
name = "fed-auth-verifier"
authors = ["Erik Davidsson <fed@icelk.dev>"]
version = "0.1.0"
edition = "2024"

[dependencies]
jsonwebtoken.workspace = true
poem.workspace = true
poem-openapi.workspace = true
reqwest.workspace = true
serde.workspace = true

[dev-dependencies]
sqlx.workspace = true

[lints]
workspace = true
