[package]
name = "fed-auth-verifier"
authors = ["Erik Davidsson <fed@icelk.dev>"]
version = "0.1.0"
edition = "2024"

[dependencies]
base64.workspace = true
color-eyre.workspace = true
ed25519-dalek.workspace = true
jsonwebtoken.workspace = true
minilith-errors = { version = "0.1.0", path = "../minilith-errors" }
opentelemetry.workspace = true
opentelemetry-semantic-conventions.workspace = true
poem.workspace = true
poem-openapi.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true

[dev-dependencies]
sqlx.workspace = true

[lints]
workspace = true
