[package]
name = "fed-tickets"
version = "0.1.0"
edition = "2024"

[dependencies]
chacha20 = "0.10.0"
color-eyre.workspace = true
dotenvy.workspace = true
hex = "0.4.3"
poem.workspace = true
poem-openapi.workspace = true
rand = "0.10.1"
sqlx.workspace = true
time = "0.3.47"
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
