[package]
name = "minilith-errors"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre.workspace = true
dotenvy.workspace = true
git-version = "0.3.9"
html-escape = "0.2.14"
lettre.workspace = true
opentelemetry.workspace = true
poem.workspace = true
poem-openapi.workspace = true
sqlx = { workspace = true, optional = true }
tokio = { workspace = true, features = ["rt"] }
tracing.workspace = true
uuid.workspace = true

[features]
sqlx = ["dep:sqlx"]

[lints]
workspace = true
