[package]
name = "bin-common"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre.workspace = true
opentelemetry.workspace = true
opentelemetry-appender-tracing.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry_sdk.workspace = true
sqlx.workspace = true
sqlx-tracing.workspace = true
tracing.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
