[package]
name = "fed-auth"
authors = ["Erik Davidsson <fed@icelk.dev>"]
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
color-eyre = "0.6.5"
dotenvy = "0.15.7"
ed25519-dalek = "2.2.0"
jsonwebtoken = { version = "10.3.0", default-features = false, features = ["rust_crypto"] }
poem = "3.1.12"
poem-openapi = { version = "5.1.16", features = ["swagger-ui", "uuid"] }
samael = "0.0.20"
serde = { version = "1.0.228", features = ["derive"] }
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio", "uuid"] }
tokio = { version = "1.52.1", features = ["fs", "rt-multi-thread", "macros", "sync"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
uuid = "1.23.1"

[lints]
workspace = true
