[package]
name = "fed-auth"
authors = ["Erik Davidsson <fed@icelk.dev>"]
version = "0.1.0"
edition = "2024"

[[bin]]
name = "fed-auth"
path = "src/main.rs"

[dependencies]
base64.workspace = true
bin-common = { version = "0.1.0", path = "../bin-common" }
color-eyre.workspace = true
dotenvy.workspace = true
ed25519-dalek.workspace = true
fed-auth-verifier.path = "../fed-auth-verifier"
jsonwebtoken.workspace = true
lettre.workspace = true
mini-moka = "0.10.3"
minilith-errors = { version = "0.1.0", path = "../minilith-errors" }
openssl = "0.10.79"
opentelemetry.workspace = true
opentelemetry-semantic-conventions.workspace = true
poem.workspace = true
poem-openapi.workspace = true
rand.workspace = true
reqwest.workspace = true
#samael = "0.0.20"
samael = { git = "https://github.com/njaremko/samael.git", rev = "f879f1942ec1b34b6d3027ce7e4724ad95d15dfa" }
serde.workspace = true
serde_json.workspace = true
serde_urlencoded = "0.7.1"
sha2 = "0.11.0"
sqlx.workspace = true
sqlx-tracing.workspace = true
tokio = { workspace = true, features = ["fs", "rt-multi-thread", "macros", "sync"] }
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
# we need an xml library where we can change the structure and add stuff, while preserving all the data.
# this seemed to be the only one to preserve e.g. prefixes (the `md` in `<md:Extensions>`).
# tested: quick-xml, serde-xml-rs
xmltree = { version = "0.12.0", features = ["attribute-order"] }

[dev-dependencies]
poem = { workspace = true, features = ["test"] }

[lints]
workspace = true
