name: CLA Sign

on:
  issue_comment:
    types: [created]

jobs:
  sign:
    uses: lth-fed/hooks/.github/workflows/cla-sign.yml@main
    permissions:
      contents: write
      actions: write
      pull-requests: read
