name: CLA Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  cla-check:
    uses: lth-fed/hooks/.github/workflows/cla-check.yml@callable-workflows
    permissions:
      contents: read
      pull-requests: write
