name: Commit Convention

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-commits:
    uses: lth-fed/hooks/.github/workflows/commit-convention.yml@callable-workflows
    permissions:
      contents: read
      pull-requests: write
