name: Cargo Build & Test

on: push

env: 
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  build_and_test:
    name: Rust CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt-get install libxmlsec1-dev pkg-config
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --workspace
      - run: cargo test --workspace
      - run: cargo clippy --workspace -- -D warnings
